// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/idfm/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/idfm/[...path]').default>>>>
    }
    '/api/lines/:lineId/topology': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lines/[lineId]/topology.get').default>>>>
    }
    '/api/lines/:transportType/:lineId/pattern': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lines/[transportType]/[lineId]/pattern.get').default>>>>
    }
    '/api/netex/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/netex/status.get').default>>>>
    }
    '/api/traffic': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/traffic.get').default>>>>
    }
    '/api/weather': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/weather.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}