// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ha/v1/boards': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/boards.post').default>>>>
    }
    '/api/ha/v1/catalog/directions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/catalog/directions.get').default>>>>
    }
    '/api/ha/v1/catalog/families': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/catalog/families.get').default>>>>
    }
    '/api/ha/v1/catalog/lines': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/catalog/lines.get').default>>>>
    }
    '/api/ha/v1/catalog/stations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/catalog/stations.get').default>>>>
    }
    '/api/ha/v1/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ha/v1/info.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/idfm/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/idfm/[...path]').default>>>>
    }
    '/api/lines/:lineId/topology': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lines/[lineId]/topology.get').default>>>>
    }
    '/api/lines/:transportType/:lineId/pattern': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lines/[transportType]/[lineId]/pattern.get').default>>>>
    }
    '/api/netex/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/netex/status.get').default>>>>
    }
    '/api/opendata/arrets-lignes/records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/opendata/arrets-lignes/records.get').default>>>>
    }
    '/api/traffic': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/traffic.get').default>>>>
    }
    '/api/transfer-bundles': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transfer-bundles.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transfer-bundles.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transfer-bundles.post').default>>>>
    }
    '/api/weather': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/weather.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}