import type { Component } from "vue";
import {
  BaggageClaim,
  BatteryLow,
  CircleAlert,
  CircleX,
  CloudLightning,
  HeartPulse,
  Info,
  Megaphone,
  Music,
  PackageSearch,
  PartyPopper,
  PawPrint,
  Settings,
  ShieldAlert,
  SignalZero,
  Siren,
  TreePine,
  TriangleAlert,
  UsersRound,
  Wrench,
} from "lucide-vue-next";
import type { PatternTrafficSummaryIncidentType } from "./trafficCalendarSummary";

export const trafficIncidentIcons: Record<
  PatternTrafficSummaryIncidentType,
  Component
> = {
  interruption: CircleX,
  works: Wrench,
  slowdown: TriangleAlert,
  crowding: UsersRound,
  strike: Megaphone,
  weather: CloudLightning,
  concert: Music,
  celebration: PartyPopper,
  animal: PawPrint,
  "fallen-tree": TreePine,
  luggage: BaggageClaim,
  signalling: SignalZero,
  "suspicious-package": PackageSearch,
  medical: HeartPulse,
  "train-breakdown": BatteryLow,
  police: Siren,
  safety: ShieldAlert,
  technical: Settings,
  incident: CircleAlert,
  information: Info,
};
