import { runNetworkTask } from "../../services/networkScheduler";
import { toServerApiUrl } from "../../services/serverApi";

export type PublicVerdictCategoryId = "transport" | "daily-life" | "nature-leisure" | "health" | "education" | "living-environment" | "security";

/** Must match the compiled verdict artifact generated by idfm-node-backend. */
export const PUBLIC_NEIGHBORHOOD_VERDICT_SCHEMA_VERSION = "1.1" as const;

export interface PublicVerdictEvidence {
  id: string;
  category: PublicVerdictCategoryId;
  polarity: "positive" | "negative" | "neutral";
  family: string;
  priority: number;
  label: string;
  explanation: string;
  rule: string;
  proof: "direct" | "derived";
  observedAt: string;
  referencePeriod?: string;
  value?: number | string;
  unit?: string;
  geography?: {
    level: "point" | "commune" | "department" | "region";
    code?: string;
    name?: string;
  };
  sourceIds: string[];
}

export interface PublicVerdictCategory {
  id: PublicVerdictCategoryId;
  status: "available" | "unavailable" | "stale";
  score?: number;
  scoreDelta?: number;
  positiveFacts: PublicVerdictEvidence[];
  negativeFacts: PublicVerdictEvidence[];
  /** Optional on the wire for compatibility with older backend snapshots. */
  neutralFacts?: PublicVerdictEvidence[];
  limitations: string[];
}

export interface PublicFutureGpeStation {
  id: string;
  name: string;
  line: string;
  lon: number;
  lat: number;
  projectStatus?: string;
  openingWindow?: string;
  /** A routed walking duration; values above 15 min are retained so a
   * co-located current hub can still be checked by the local score engine. */
  walkingMinutes?: number;
  hubId?: string;
  coLocatedCurrentLineCodes?: readonly string[];
  verifiedAt?: string;
}

/**
 * A named, large green-space site exposed as a route target. The backend
 * keeps a projected site boundary target plus a few deterministic transit
 * points; the frontend probes the shared transit router when walking is not
 * competitive.
 */
export interface PublicGreenSpaceRoutePoint {
  lon: number;
  lat: number;
}

export interface PublicGreenSpaceAccess {
  id: string;
  name: string;
  category?: string;
  surfaceM2?: number;
  lon: number;
  lat: number;
  distanceMeters: number;
  walkingMinutes?: number;
  estimatedWalkingMinutes: number;
  transitPoints?: PublicGreenSpaceRoutePoint[];
}

export interface PublicVerdictSource {
  id: string;
  title: string;
  producer: string;
  pageUrl: string;
  referencePeriod?: string;
  fetchedAt?: string;
  licence: { label: string; url?: string; attribution: string };
  freshness: { status: "fresh" | "aging" | "stale"; checkedAt: string; ageDays: number };
  limitations: string[];
}

export interface PublicNeighborhoodVerdict {
  schemaVersion: typeof PUBLIC_NEIGHBORHOOD_VERDICT_SCHEMA_VERSION;
  generatedAt: string;
  categories: PublicVerdictCategory[];
  futureProjects?: PublicFutureGpeStation[];
  nearbyGreenSpaces?: PublicGreenSpaceAccess[];
  security?: {
    commune?: string;
    trend?: string;
    indicators?: Array<Record<string, unknown>>;
  };
  sources: PublicVerdictSource[];
  warnings: string[];
}

export async function fetchNeighborhoodVerdict(lat: number, lon: number, signal?: AbortSignal): Promise<PublicNeighborhoodVerdict> {
  return runNetworkTask(async (signal) => {
    const params = new URLSearchParams({ lat: String(lat), lon: String(lon) });
    const response = await fetch(toServerApiUrl(`/api/neighborhood-verdict?${params}`), { signal });
    if (!response.ok) throw new Error(`Neighborhood verdict unavailable (${response.status})`);
    const payload = await response.json() as PublicNeighborhoodVerdict;
    if (payload.schemaVersion !== PUBLIC_NEIGHBORHOOD_VERDICT_SCHEMA_VERSION || !Array.isArray(payload.categories) || !Array.isArray(payload.sources)) throw new Error("Unsupported neighborhood verdict contract");
    return {
      ...payload,
      categories: payload.categories.map((category) => ({
        ...category,
        positiveFacts: Array.isArray(category.positiveFacts) ? category.positiveFacts : [],
        negativeFacts: Array.isArray(category.negativeFacts) ? category.negativeFacts : [],
        neutralFacts: Array.isArray(category.neutralFacts) ? category.neutralFacts : [],
      })),
    };
  }, signal);
}
