import { NEWS_MODES, type NewsMode, type NewsSource } from "./types";

const rss = (
  id: string,
  name: string,
  url: string,
  mode?: NewsMode,
  codes: string[] = [],
  regional = true,
  kind: NewsSource["kind"] = "official",
  topics?: NewsSource["topics"],
  areas?: string[],
): NewsSource => ({
  id,
  name,
  url,
  method: "rss",
  kind,
  regional,
  topics,
  areas,
  modes: mode ? [mode] : [...NEWS_MODES],
  lines: mode ? codes.map((code) => ({ mode, code })) : undefined,
});
const html = (
  id: string,
  name: string,
  url: string,
  articlePath: string,
  modes: NewsMode[] = [...NEWS_MODES],
  topics?: NewsSource["topics"],
  areas?: string[],
): NewsSource => ({
  id,
  name,
  url,
  articlePath,
  modes,
  method: "html",
  kind: "official",
  regional: true,
  topics,
  areas,
});
export const NEWS_SOURCES: NewsSource[] = [
  rss("rer-a", "RER A", "https://malignea.fr/feed/", "rer", ["A"]),
  rss("rer-b", "RER B", "https://maligneb.fr/feed/", "rer", ["B"]),
  {
    ...rss(
      "rer-c-v",
      "RER C / Transilien V",
      "https://monrercetlignev.transilien.com/feed/",
      "rer",
      ["C"],
    ),
    modes: ["rer", "train"],
    lines: [
      { mode: "rer", code: "C" },
      { mode: "train", code: "V" },
    ],
  },
  rss("rer-d", "RER D", "https://maligned.transilien.com/feed/", "rer", ["D"]),
  rss("rer-e", "RER E", "https://malignee.transilien.com/feed/", "rer", ["E"]),
  ...["h", "j", "l", "p", "r"].map((code) =>
    rss(
      `transilien-${code}`,
      `Transilien ${code.toUpperCase()}`,
      `https://maligne${code}.transilien.com/feed/`,
      "train",
      [code.toUpperCase()],
    ),
  ),
  rss("transilien-n-u", "Transilien N / U", "https://malignen.transilien.com/feed/", "train", [
    "N",
    "U",
  ]),
  rss("transbus", "Transbus", "https://www.transbus.org/push_rss.rss", "bus", [], false, "press"),
  rss(
    "journal-grand-paris",
    "Le Journal du Grand Paris",
    "https://www.lejournaldugrandparis.fr/feed/",
    undefined,
    [],
    true,
    "press",
  ),
  rss("citoyens", "Citoyens", "https://94.citoyens.com/feed", undefined, [], true, "press"),
  rss(
    "actu-idf",
    "Actu Île-de-France",
    "https://actu.fr/ile-de-france/rss.xml",
    undefined,
    [],
    true,
    "press",
  ),
  rss("chatenay", "Châtenay-Malabry", "https://www.chatenay-malabry.fr/feed/", undefined, [], true, "official", undefined, ["Châtenay-Malabry"]),
  rss("bagneux", "Bagneux", "https://www.bagneux92.fr/78/flux-rss-des-actualites.xml", undefined, [], true, "official", undefined, ["Bagneux"]),
  rss(
    "idfm-presse",
    "Île-de-France Mobilités — Presse",
    "https://presse.iledefrance-mobilites.fr/feed/",
  ),
  html(
    "grand-paris",
    "Société des grands projets",
    "https://www.societedesgrandsprojets.fr/actualites",
    "/actualites/",
    ["metro", "train", "rer"],
  ),
  html(
    "region-idf",
    "Région Île-de-France",
    "https://www.iledefrance.fr/toutes-les-actualites",
    "/toutes-les-actualites/",
  ),
  html("ratp", "RATP", "https://www.ratp.fr/actualites", "/actualites/"),
  html(
    "sncf-reseau",
    "SNCF Réseau — Île-de-France",
    "https://www.sncf-reseau.com/fr/en-ile-france-service-lhyper-mobilite",
    "/fr/",
    ["rer", "train", "tram"],
  ),
  html(
    "cd92",
    "Hauts-de-Seine",
    "https://www.hauts-de-seine.fr/toutes-les-actualites",
    "/toutes-les-actualites/detail/",
  ),
  html(
    "cd94",
    "Val-de-Marne",
    "https://www.valdemarne.fr/vivre-en-val-de-marne/actualites",
    "/vivre-en-val-de-marne/actualites/",
  ),
  html("cd93", "Seine-Saint-Denis", "https://seinesaintdenis.fr/actualite", "/actualite/"),
  html("cd77", "Seine-et-Marne", "https://www.seine-et-marne.fr/fr/actualites", "/fr/actualites/"),
  html("cd78", "Yvelines", "https://www.yvelines.fr/actualites/", "/actualites/"),
  html("cd91", "Essonne", "https://www.essonne.fr/", "/actualites/"),
  html(
    "cd95",
    "Val-d’Oise",
    "https://www.valdoise.fr/liste-actualite/175-actualites.htm",
    "/actualite/",
  ),
  html("paris", "Ville de Paris", "https://www.paris.fr/actualites", "/pages/", [...NEWS_MODES], undefined, ["Paris"]),
  html("clamart", "Clamart", "https://www.clamart.fr/fr/actualites", "/fr/actualites/", [...NEWS_MODES], undefined, ["Clamart"]),
  html("bourg-la-reine", "Bourg-la-Reine", "https://www.bourg-la-reine.fr/", "/actualite/", [...NEWS_MODES], undefined, ["Bourg-la-Reine"]),
  html(
    "institut-paris-region",
    "Institut Paris Region — Presse et urbanisme",
    "https://www.institutparisregion.fr/presse/",
    "/presse/",
    [...NEWS_MODES],
    ["urbanism", "realEstate"],
  ),
  html(
    "notaires-grand-paris",
    "Notaires du Grand Paris — Immobilier",
    "https://notairesdugrandparis.fr/fr/liste-communiques-de-presse",
    "/fr/presse/communication-immobiliere-mensuelle/",
    [...NEWS_MODES],
    ["realEstate"],
  ),
  html(
    "grand-paris-amenagement",
    "Grand Paris Aménagement",
    "https://www.grandparisamenagement.fr/publications",
    "/publications/",
    [...NEWS_MODES],
    ["urbanism", "realEstate"],
  ),
  html(
    "metropole-grand-paris",
    "Métropole du Grand Paris — Aménagement",
    "https://www.metropolegrandparis.fr/fr/actualites",
    "/fr/actualites/",
    [...NEWS_MODES],
    ["urbanism"],
  ),
  {
    ...html(
      "t1-val-fontenay",
      "T1 — Bobigny / Val de Fontenay",
      "https://www.t1bobigny-valdefontenay.fr/fr/actualites",
      "/fr/actualites/",
      ["tram"],
    ),
    lines: [{ mode: "tram", code: "T1" }],
  },
  {
    id: "t10-clamart",
    name: "IDFM — T10 vers Clamart",
    url: "https://www.iledefrance-mobilites.fr/le-reseau/projets/tram-t10-prolongement/actualites",
    method: "html",
    kind: "official",
    regional: true,
    articlePath: "/tram-t10-prolongement/actualites/",
    modes: ["tram"],
    lines: [{ mode: "tram", code: "T10" }],
  },
  {
    id: "t10-cndp",
    name: "CNDP — concertation du prolongement du T10",
    url: "https://www.debatpublic.fr/projet-de-prolongement-du-tramway-t10-clamart-vers-la-future-ligne-15-du-metro-3235",
    method: "article",
    kind: "official",
    regional: true,
    modes: ["tram"],
    lines: [{ mode: "tram", code: "T10" }],
  },
  {
    id: "t10-chatenay",
    name: "Châtenay-Malabry — prolongement du T10",
    url: "https://www.chatenay-malabry.fr/le-tramway-t10-et-son-prolongement-jusqua-la-ligne-15-du-grand-paris-express/",
    method: "article",
    kind: "official",
    regional: true,
    modes: ["tram"],
    lines: [{ mode: "tram", code: "T10" }],
  },
  {
    id: "t10-cd92",
    name: "Hauts-de-Seine — projet du tramway T10",
    url: "https://www.hauts-de-seine.fr/mon-departement/les-hauts-de-seine/les-grands-projets/les-infrastructures-de-transport/tramways/le-tramway-t10",
    method: "article",
    kind: "official",
    regional: true,
    modes: ["tram"],
    lines: [{ mode: "tram", code: "T10" }],
  },
  {
    id: "m4-chatenay",
    name: "Châtenay-Malabry — prolongement du M4",
    url: "https://www.chatenay-malabry.fr/prolongement-de-la-ligne-4-du-metro-jusqua-chatenay-malabry/",
    method: "article",
    kind: "official",
    regional: true,
    modes: ["metro"],
    lines: [{ mode: "metro", code: "4" }],
  },
];
